Adding the intial lexer
cat-dev-group/meow.c pull request #6
Opened 2021-11-19 01:17 UTC by AbooMinister25

This code has the initial code for the lexer, it supports a variety of single and double character tokens, integers, strings, bools, identifiers, and keywords. It also has the initial style changes from camelCase to snake_case.

2021-11-19 01:38 UTC, dawnofmidnight requested changes
Other than the following comments, this looks great! I'm probably forgetting some really important things somewhere, but I'll review again later on.

2021-11-19 01:38 UTC, dawnofmidnight commented on src/main.c
>  }
I can't comment below this line, but might we want some intro to the repl? Something like this, maybe?
```
Meow 0.1.0. For help, type `:help`
> 
```

2021-11-19 01:38 UTC, dawnofmidnight commented on src/tokens.h
> +    T_RBRACE,
We also want `LBracket` and `RBracket`, right?

2021-11-19 01:38 UTC, dawnofmidnight commented on src/lexer.c
> +            return create_token(lexer, T_SLASH);
When testing, I noticed that the lexer hangs on any slash. Also, are we not including comments in this initial iteration?

2021-11-19 03:25 UTC, AbooMinister25 commented on src/lexer.c
> +            return create_token(lexer, T_SLASH);
There are comments, they're handled in the skip_whitespace function, and are only handled if two successive slashes are found

2021-11-19 03:25 UTC, AbooMinister25 commented on src/main.c
>  }
Sure, we can do that

2021-11-19 03:25 UTC, AbooMinister25 commented on src/tokens.h
> +    T_RBRACE,
Oop, I'll get that down

2021-11-19 03:27 UTC, dawnofmidnight commented on src/lexer.c
> +            return create_token(lexer, T_SLASH);
Ah, ok

2021-11-19 03:27 UTC, dawnofmidnight commented on src/lexer.c
> +            return create_token(lexer, T_SLASH);
Although the hanging thing, I don't know. It might just be a repl thing, but the thing just died there.

2021-11-19 03:36 UTC, AbooMinister25 commented on src/lexer.c
> +            return create_token(lexer, T_SLASH);
Yeah, I'll look into that tomorrow

2021-11-20 20:50 UTC, doublevcodes approved these changes
Lookin' decent

2021-11-20 20:50 UTC, doublevcodes commented on src/vm.h
> +void free_vm(VM *vm); // Function that frees the Lite VM from memory.
Uhh... Lite?

2021-11-20 21:13 UTC, dawnofmidnight approved these changes

2021-11-20 21:13 UTC, merged